apiVersion: v1
kind: Service
metadata:
  name: {{ include "medgrid-chart.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}