apiVersion: v1
kind: Secret
metadata:
  name: medgrid-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_URI: {{ printf "mongodb://%s:%s@%s:27017/?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&tlsCAFile=/etc/pki/tls/certs/rds-combined-ca-bundle.pem" .Values.mongodb.username .Values.mongodb.password .Values.mongodb.uri | b64enc }}